compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: /mnt/workspace/haoaiming.ham/codes/Video-Generation/HunyuanVideo/config/deepspeed/ds_config_multi_node.json
  deepspeed_hostfile: ''
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
main_training_function: main
rdzv_backend: static
same_network: false
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
